name: Circuitman
version: "0.0.2"
description: "Unleash your inner computer nerd (and chaotic self)"
main: com.boyninja1555.circuitman.Circuitman
api-version: "1.21"
folia-supported: true

authors:
    - boyninja1555